# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-operator
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: garage
  interval: 1h
  prune: true
  sourceRef:
    kind: OCIRepository
    name: garage-s3-operator
    namespace: flux-system
  wait: true
