---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

ui:
  title: Status | Home Operations
  header: Status
  logo: https://raw.githubusercontent.com/rcdailey/home-ops/main/kubernetes/apps/observability/gatus/resources/logo.png
  link: https://github.com/rcdailey
  buttons:
  - name: Github
    link: https://github.com/rcdailey/home-ops

endpoints:
- name: Internet Connectivity
  url: icmp://1.1.1.1
  interval: 1m
  conditions:
  - "[CONNECTED] == true"

- name: Bazarr
  group: media
  url: http://bazarr.media:6767/health
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Jellyseerr
  group: media
  url: http://jellyseerr.media:80
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Plex
  group: media
  url: http://plex.media:32400/identity
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Prowlarr
  group: media
  url: http://prowlarr.media:9696/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: qBittorrent
  group: media
  url: http://qbittorrent.media:8080
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Radarr
  group: media
  url: http://radarr.media:7878/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Radarr 4K
  group: media
  url: http://radarr-4k.media:7878/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Radarr Anime
  group: media
  url: http://radarr-anime.media:7878/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: SABnzbd
  group: media
  url: http://sabnzbd.media:8080/api?mode=version
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Sonarr
  group: media
  url: http://sonarr.media:8989/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Sonarr Anime
  group: media
  url: http://sonarr-anime.media:8989/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Tautulli
  group: media
  url: http://tautulli.media:8181/status
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Home Assistant
  group: home
  url: http://home-assistant.home:8123
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: ESPHome
  group: home
  url: http://esphome.home:6052
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Z-Wave JS UI
  group: home
  url: http://zwave-js-ui.home:80/health
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Authelia
  group: default
  url: http://authelia-app.default:9091
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: BookStack
  group: default
  url: http://bookstack-app.default:8080
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Immich
  group: default
  url: http://immich-app.default:2283/api/server/ping
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: OpenCloud
  group: default
  url: http://opencloud-app.default:9200
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: AdGuard Home
  group: dns-private
  url: http://adguard-home.dns-private:3000
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Grafana
  group: observability
  url: http://grafana.observability:80/api/health
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: VictoriaLogs
  group: observability
  url: http://victoria-logs-single.observability:9428/health
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: VictoriaMetrics
  group: observability
  url: http://vmsingle-victoria-metrics-k8s-stack.observability:8428/health
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Headlamp
  group: kube-system
  url: http://headlamp.kube-system:80
  interval: 1m
  conditions:
  - "[STATUS] == 200"

- name: Garage
  group: storage
  url: http://garage.storage:3903
  interval: 1m
  conditions:
  - "[STATUS] == 200"

external-endpoints:
- name: Heartbeat
  token: ${GATUS_HEARTBEAT_TOKEN}
  heartbeat:
    interval: 10m

web:
  port: ${GATUS_WEB_PORT}
