---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
- ../../components/common
- ../../components/drift-detection
resources:
- ./bazarr/ks.yaml
- ./imagemaid/ks.yaml
- ./jellyseerr/ks.yaml
- ./kometa/ks.yaml
- ./plex/ks.yaml
- ./plexanisync/ks.yaml
- ./prowlarr/ks.yaml
- ./qbittorrent/ks.yaml
- ./radarr/ks.yaml
- ./radarr-4k/ks.yaml
- ./radarr-anime/ks.yaml
- ./recyclarr/ks.yaml
- ./sabnzbd/ks.yaml
- ./sonarr/ks.yaml
- ./sonarr-anime/ks.yaml
- ./tautulli/ks.yaml
