[env]
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tools]
"aqua:budimanjojo/talhelper" = "3.0.44"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "4.0.4"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:talosctl" = "1.11.6"
"asdf:bitwarden-secrets-manager" = "latest"
gitleaks = "latest"
python = "3.14.2"
