[env]
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
DIFFTOOL = "delta"

[tools]
crane = "latest"
delta = "latest"
flux2 = "2.8.0"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
gum = "latest"
helm = "4.1.1"
helmfile = "latest"
infisical = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kubectl = "1.35.2"
kustomize = "latest"
markdownlint-cli2 = "latest"
pre-commit = "latest"
python = "3.14.3"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
talosctl = "1.12.4"
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"

[hooks.enter]
shell = "zsh"
script = "eval \"$(just --completions bash)\""
