[env]
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
DIFFTOOL = "delta"

[tools]
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "4.1.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:talosctl" = "1.12.2"
"asdf:bitwarden-secrets-manager" = "latest"
gitleaks = "latest"
gum = "latest"
helmfile = "latest"
infisical = "latest"
python = "3.14.2"
ruff = "latest"
yamlfmt = "latest"
