[env]
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
DIFFTOOL = "delta"

[tools]
delta = "latest"
flux2 = "2.7.5"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
gum = "latest"
helm = "4.1.1"
helmfile = "latest"
infisical = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kubectl = "1.33.1"
kustomize = "latest"
markdownlint-cli2 = "latest"
pre-commit = "latest"
python = "3.14.3"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
talosctl = "1.12.4"
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"
