[env]
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tools]
"aqua:budimanjojo/talhelper" = "3.0.38"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "3.19.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:talosctl" = "1.11.5"
"asdf:bitwarden-secrets-manager" = "latest"
python = "3.14.0"
