---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plexanisync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: plexanisync-secret
    creationPolicy: Owner
  data:
  - secretKey: ANI_TOKEN
    remoteRef:
      key: /media/plexanisync/anilist-token
  - secretKey: ANI_USERNAME
    remoteRef:
      key: /media/plexanisync/anilist-username
  - secretKey: PLEX_TOKEN
    remoteRef:
      key: /media/plex/token
