# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: garage-secret
    creationPolicy: Owner
  data:
  - secretKey: S3_ACCESS_KEY_ID
    remoteRef:
      key: /storage/garage/access-key-id
  - secretKey: S3_SECRET_ACCESS_KEY
    remoteRef:
      key: /storage/garage/secret-access-key
  - secretKey: S3_REGION
    remoteRef:
      key: /storage/garage/region
  - secretKey: GARAGE_RPC_SECRET
    remoteRef:
      key: /storage/garage/rpc-secret
  - secretKey: GARAGE_ADMIN_TOKEN
    remoteRef:
      key: /storage/garage/admin-token
