---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./helmrelease.yaml
- ./pvc.yaml
- ./externalsecret.yaml
configMapGenerator:
- name: garage-config
  files:
  - config/garage.toml
  options:
    disableNameSuffixHash: true
