---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plexanibridge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: plexanibridge-secret
    creationPolicy: Owner
  data:
  - secretKey: PAB_ANILIST_TOKEN
    remoteRef:
      key: /media/plexanibridge/anilist-token
  - secretKey: PAB_PLEX_TOKEN
    remoteRef:
      key: /media/plex/token
  - secretKey: PAB_PLEX_USER
    remoteRef:
      key: /media/plex/user
