---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plexanibridge
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      plexanibridge:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/eliasbenb/plexanibridge
              tag: v1.10.1

            env:
              TZ: America/Chicago
              PAB_PLEX_URL: http://plex.media:32400
              PAB_PLEX_SECTIONS: '["Anime Series", "Anime Movies"]'
              PAB_SYNC_MODES: '["webhook"]'
              PAB_EXCLUDED_SYNC_FIELDS: '["notes"]'
              PAB_BACKUP_RETENTION_DAYS: "1"
              PAB_DATA_PATH: /config

            envFrom:
            - secretRef:
                name: plexanibridge-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &spec
                  httpGet:
                    path: /api/system/meta
                    port: 4848
              readiness: *probes
              startup:
                !!merge <<: *probes
                spec:
                  !!merge <<: *spec
                  periodSeconds: 5
                  failureThreshold: 8

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

            securityContext:
              runAsUser: 0
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: [ALL]
                add: [CHOWN, SETUID, SETGID]

    persistence:
      config:
        existingClaim: plexanibridge-config
        advancedMounts:
          plexanibridge:
            app:
            - path: /config

      tmp:
        type: emptyDir
        advancedMounts:
          plexanibridge:
            app:
            - path: /tmp

      home:
        type: emptyDir
        advancedMounts:
          plexanibridge:
            app:
            - path: /home

    service:
      app:
        controller: plexanibridge
        ports:
          http:
            port: 4848

    route:
      app:
        hostnames:
        - plexanibridge.${SECRET_DOMAIN}
        parentRefs:
        - name: internal
          namespace: network
          sectionName: https
        rules:
        - backendRefs:
          - name: plexanibridge-app
            port: 4848
