# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .jwt_secret }}"
        LLDAP_KEY_SEED: "{{ .key_seed }}"
        LLDAP_LDAP_USER_PASS: "{{ .admin_password }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .admin_email }}"
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: /default/lldap/jwt-secret
  - secretKey: key_seed
    remoteRef:
      key: /default/lldap/key-seed
  - secretKey: admin_password
    remoteRef:
      key: /default/lldap/admin-password
  - secretKey: admin_email
    remoteRef:
      key: /default/lldap/admin-email
