---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: imagemaid
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      imagemaid:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          schedule: "0 3 * * *"
          timeZone: America/Chicago
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          backoffLimit: 0
          ttlSecondsAfterFinished: 3600

        pod:
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true

        containers:
          app:
            image:
              repository: kometateam/imagemaid
              tag: v1.1.1@sha256:fbec331b36c1473f8a9c4214f55e5b097860476c8a5274eb61a2b85df89e56cc
            env:
              TZ: America/Chicago
              PLEX_URL: http://plex.media:32400
              MODE: remove
              LOCAL_DB: "false"
              IGNORE_RUNNING: "true"
              PHOTO_TRANSCODER: "false"
              OPTIMIZE_DB: "false"
              EMPTY_TRASH: "false"
              CLEAN_BUNDLES: "false"
              TIMEOUT: "600"
              SLEEP: "60"
              TRACE: "false"
              LOG_REQUESTS: "false"
            envFrom:
            - secretRef:
                name: imagemaid-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: imagemaid
        advancedMounts:
          imagemaid:
            app:
            - path: /config

      tmp:
        type: emptyDir
        advancedMounts:
          imagemaid:
            app:
            - path: /tmp
