---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr-anime:
    base_url: !env_var SONARR_ANIME_BASE_URL http://sonarr-anime.media:8989
    api_key: !env_var SONARR_ANIME_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: anime

    quality_profiles:
    - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
      name: Remux-1080p - Anime
      reset_unmatched_scores:
        enabled: true

    media_naming:
      series: plex-imdb
      season: default
      episodes:
        rename: true
        anime: default

    custom_formats:
    - trash_ids:
      - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
      assign_scores_to:
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f
        score: 101 # Adjust scoring as desired
