---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr-series:
    base_url: !env_var SONARR_BASE_URL http://sonarr.media:8989
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: series

    quality_profiles:
    - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
      name: WEB-1080p
      reset_unmatched_scores:
        enabled: true
    - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
      name: WEB-2160p
      reset_unmatched_scores:
        enabled: true

    custom_format_groups:
      add:
      - trash_id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback)
      - trash_id: 7d366c213e5c23a052b157356fac1921 # [HDR Formats] HDR10+ Boost
