# Services organized by usage frequency: frequently used expanded, rarely used collapsed
---
# Expanded sections (frequently used)
- Favorites:
  - Jellyseerr:
      icon: jellyseerr
      href: https://request.${SECRET_DOMAIN}/
      siteMonitor: http://jellyseerr.media:80

  - Immich:
      icon: immich
      href: https://photos.${SECRET_DOMAIN}/
      siteMonitor: http://immich.default:2283

  - Home Assistant:
      icon: home-assistant
      href: https://ha.${SECRET_DOMAIN}/
      siteMonitor: http://home-assistant.home:8123

  - Tautulli:
      icon: tautulli
      href: https://tautulli.${SECRET_DOMAIN}/
      siteMonitor: http://tautulli.media:8181

  - BookStack:
      icon: bookstack
      href: https://wiki.${SECRET_DOMAIN}/
      siteMonitor: http://bookstack.default:8080/status

  - OpenCloud:
      icon: mdi-cloud
      href: https://cloud.${SECRET_DOMAIN}/
      siteMonitor: http://opencloud.default:9200

  - Grafana:
      icon: grafana
      href: https://grafana.${SECRET_DOMAIN}/
      siteMonitor: http://grafana-service.observability:3000/api/health

  - Donetick:
      icon: donetick
      href: https://tasks.${SECRET_DOMAIN}/
      siteMonitor: http://donetick.default:2021/api/v1/ping

- Media:
  - Qui:
      icon: qbittorrent
      href: https://qui.${SECRET_DOMAIN}/
      siteMonitor: http://qui.media:7476

  - Sabnzbd:
      icon: sabnzbd
      href: https://nzb.${SECRET_DOMAIN}/
      siteMonitor: http://sabnzbd.media:8080

  - Sonarr:
      icon: sonarr
      href: https://sonarr.${SECRET_DOMAIN}/
      siteMonitor: http://sonarr.media:8989

  - Sonarr (Anime):
      icon: sonarr
      href: https://sonarr-anime.${SECRET_DOMAIN}/
      siteMonitor: http://sonarr-anime.media:8989

  - Radarr (4K):
      icon: radarr
      href: https://radarr-4k.${SECRET_DOMAIN}/
      siteMonitor: http://radarr-4k.media:7878

  - Radarr:
      icon: radarr
      href: https://radarr.${SECRET_DOMAIN}/
      siteMonitor: http://radarr.media:7878

  - Radarr (Anime):
      icon: radarr
      href: https://radarr-anime.${SECRET_DOMAIN}/
      siteMonitor: http://radarr-anime.media:7878

  - Prowlarr:
      icon: prowlarr
      href: https://prowlarr.${SECRET_DOMAIN}/
      siteMonitor: http://prowlarr.media:9696

  - Bazarr:
      icon: bazarr
      href: https://bazarr.${SECRET_DOMAIN}/
      siteMonitor: http://bazarr.media:6767

  - Plex:
      icon: plex
      href: https://plex.${SECRET_DOMAIN}/
      siteMonitor: http://plex.media:32400

  - qBittorrent:
      icon: qbittorrent
      href: https://torrent.${SECRET_DOMAIN}/
      siteMonitor: http://qbittorrent.media:8080

- Home Automation:
  - ESPHome:
      icon: esphome
      href: https://esphome.${SECRET_DOMAIN}/
      siteMonitor: http://esphome.home:6052

  - Z-Wave JS UI:
      icon: z-wave-js-ui
      href: https://zwave.${SECRET_DOMAIN}/
      siteMonitor: http://zwave-js-ui.home:80

  - Zigbee/Z-Wave/Thread Hub:
      icon: mdi-zigbee
      href: http://192.168.1.64
      ping: 192.168.1.64

  - Open Sprinkler:
      icon: opensprinkler
      href: https://sprinkler.${SECRET_DOMAIN}/
      siteMonitor: http://opensprinkler.external:80

- Infrastructure:
  - Headlamp:
      icon: kubernetes
      href: https://cluster.${SECRET_DOMAIN}/
      siteMonitor: http://headlamp.default:80

  - Pocket-ID:
      icon: pocket-id
      href: https://auth.${SECRET_DOMAIN}/
      siteMonitor: http://pocket-id.default:1411

  - VS Code:
      icon: vscode
      href: https://code.${SECRET_DOMAIN}/
      siteMonitor: http://code-server.home:8080

  - Unraid:
      icon: unraid
      href: http://192.168.1.58/Dashboard
      ping: 192.168.1.58

  - Unifi (local):
      icon: ubiquiti-unifi
      href: https://192.168.1.1/
      ping: 192.168.1.1

  - AT&T Gateway:
      icon: mdi-router-wireless
      href: http://192.168.99.254/cgi-bin/home.ha
      ping: 192.168.99.254

  - HDHomeRun:
      icon: hdhomerun
      href: http://192.168.1.53/
      ping: 192.168.1.53

  - CUPS Print Server:
      icon: cups
      href: http://192.168.1.52:631/
      ping: 192.168.1.52

  - APC SmartConnect:
      icon: apc
      href: https://smartconnect.apc.com/

- Monitoring:
  - VictoriaMetrics:
      icon: victoriametrics
      href: https://victoria-metrics.${SECRET_DOMAIN}/
      siteMonitor: http://vmsingle-victoria-metrics-k8s-stack.observability:8428/health

  - VictoriaLogs:
      icon: victorialogs
      href: https://victoria-logs.${SECRET_DOMAIN}/
      siteMonitor: http://victoria-logs-single.observability:9428/health

  - VM AlertManager:
      icon: alertmanager
      href: https://vmalertmanager.${SECRET_DOMAIN}/
      siteMonitor: http://vmalertmanager-victoria-metrics-k8s-stack.observability:9093/-/healthy

  - VM Alert:
      icon: mdi-alert-octagon
      href: https://vmalert.${SECRET_DOMAIN}/
      siteMonitor: http://vmalert-victoria-metrics-k8s-stack.observability:8080/-/healthy

  - Ceph Dashboard:
      icon: ceph
      href: https://ceph.${SECRET_DOMAIN}/
      siteMonitor: http://rook-ceph-mgr-dashboard.rook-ceph:7000

  - Kopia:
      icon: kopia
      href: https://kopia.${SECRET_DOMAIN}/
      siteMonitor: http://kopia.storage:80
