---
title: Nami
favicon: https://raw.githubusercontent.com/rcdailey/home-ops/main/kubernetes/apps/default/homepage/icons/nami.png

theme: dark
color: slate
iconStyle: theme

# Layout: no tabs, frequently used expanded, rarely used collapsed
layout:
  Favorites:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Home Automation:
    columns: 1
  Infrastructure:
    columns: 1
  Monitoring:
    columns: 1

useEqualHeights: true
headerStyle: clean
statusStyle: dot
target: _self
maxGroupColumns: 1
fullWidth: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  provider: google

hideVersion: true
