---
- logo:
    icon: https://raw.githubusercontent.com/rcdailey/home-ops/main/kubernetes/apps/default/homepage/icons/nami.png

- search:
    provider: google
    target: _blank

- greeting:
    text_size: xl
    text: Welcome to Nami

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23

# No system or cluster widgets for public landing page
