# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/httproutefilter_v1alpha1.json
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: pocket-id-block-setup
spec:
  directResponse:
    contentType: text/plain
    statusCode: 403
    body:
      type: Inline
      inline: "Forbidden"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pocket-id-block-setup
spec:
  parentRefs:
  - name: external
    namespace: network
    sectionName: https
  hostnames:
  - auth.${SECRET_DOMAIN}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /setup
    - path:
        type: PathPrefix
        value: /signup/setup
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.envoyproxy.io
        kind: HTTPRouteFilter
        name: pocket-id-block-setup
