---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns-private
components:
- ../../components/common
resources:
- ./secret/ks.yaml
- ./external-dns/ks.yaml
- ./dns-gateway/ks.yaml
- ./blocky/ks.yaml
