# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: /default/immich/jwt-secret
  - secretKey: DB_HOSTNAME
    remoteRef:
      key: /default/immich/db-hostname
  - secretKey: DB_PORT
    remoteRef:
      key: /default/immich/db-port
  - secretKey: DB_DATABASE_NAME
    remoteRef:
      key: /default/immich/db-database-name
  - secretKey: DB_USERNAME
    remoteRef:
      key: /default/immich/db-username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /default/immich/db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: immich-postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /default/immich/db-username
  - secretKey: password
    remoteRef:
      key: /default/immich/db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: garage-secret
    creationPolicy: Owner
  data:
  - secretKey: S3_ACCESS_KEY_ID
    remoteRef:
      key: /storage/garage/access-key-id
  - secretKey: S3_SECRET_ACCESS_KEY
    remoteRef:
      key: /storage/garage/secret-access-key
  - secretKey: S3_REGION
    remoteRef:
      key: /storage/garage/region
