# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filerun-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: filerun-secret
    creationPolicy: Owner
  data:
  - secretKey: MARIADB_ROOT_PASSWORD
    remoteRef:
      key: /default/filerun/mariadb-root-password
  - secretKey: MARIADB_PASSWORD
    remoteRef:
      key: /default/filerun/mariadb-password
  - secretKey: FR_DB_PASS
    remoteRef:
      key: /default/filerun/fr-db-pass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: garage-secret
    creationPolicy: Owner
  data:
  - secretKey: S3_ACCESS_KEY_ID
    remoteRef:
      key: /storage/garage/access-key-id
  - secretKey: S3_SECRET_ACCESS_KEY
    remoteRef:
      key: /storage/garage/secret-access-key
  - secretKey: S3_REGION
    remoteRef:
      key: /storage/garage/region
