---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- ./helmrelease.yaml
- ./mariadb.yaml
- ./pvc.yaml
- ./externalsecret.yaml
- ./backendtrafficpolicy.yaml
configMapGenerator:
- name: filerun-php-config
  files:
  - config/filerun-optimization.ini
  options:
    disableNameSuffixHash: true
