# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nextcloud-secret
    creationPolicy: Owner
  data:
  - secretKey: nextcloud-username
    remoteRef:
      key: /default/nextcloud/admin-username
  - secretKey: nextcloud-password
    remoteRef:
      key: /default/nextcloud/admin-password
  - secretKey: oidc-client-secret
    remoteRef:
      key: /default/nextcloud/oidc-client-secret
  - secretKey: smtp-host
    remoteRef:
      key: /email-smtp-host
  - secretKey: smtp-username
    remoteRef:
      key: /email-smtp-user
  - secretKey: smtp-password
    remoteRef:
      key: /email-smtp-pass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nextcloud-postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /default/nextcloud/db-username
  - secretKey: password
    remoteRef:
      key: /default/nextcloud/db-password
