# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- externalsecret.yaml
- helmrelease.yaml
- httproute.yaml
- notify-push-service.yaml
- ocirepository.yaml
- postgres-cluster.yaml
- postgres-scheduled-backup.yaml
- pvc.yaml
- volsync-data-secret.yaml
- volsync-data.yaml
