# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres-backup
spec:
  schedule: 0 2 * * *
  backupOwnerReference: self
  cluster:
    name: nextcloud-postgres
  method: barmanObjectStore
  target: prefer-standby
  immediate: true
