# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-data-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: volsync-shared-kopia-password
  KOPIA_REPOSITORY: filesystem:///repository
