---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-secrets
spec:
  externalSecretName: cluster-secrets
  namespaceSelectors:
  - {}
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: cluster-secrets
      creationPolicy: Owner
    data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: secret-domain
