---
# yaml-language-server: $schema=https://raw.githubusercontent.com/vchirikov/dotfiles/master/jsonschemas/dnsendpoints.externaldns.k8s.io.schema.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  labels:
    external-dns/provider: cloudflare
spec:
  endpoints:
  - dnsName: "external.${SECRET_DOMAIN}"
    recordType: CNAME
    targets: ["6b689c5b-81a9-468e-9019-5892b3390500.cfargotunnel.com"]
