---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushover-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pushover-secret
    creationPolicy: Owner
  data:
  - secretKey: PUSHOVER_USER_KEY
    remoteRef:
      key: /observability/pushover-user-key
  - secretKey: PUSHOVER_APP_TOKEN
    remoteRef:
      key: /observability/pushover-app-token
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watchdog-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: watchdog-secret
    creationPolicy: Owner
  data:
  - secretKey: WATCHDOG_PING_URL
    remoteRef:
      key: /observability/watchdog-ping-url
