---
# yaml-language-server: $schema=https://raw.githubusercontent.com/envoyproxy/gateway/main/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: adguard-home
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: adguard-home-app
  healthCheck:
    active:
      type: HTTP
      http:
        path: /login.html
        expectedStatuses:
        - 200
      timeout: 3s
      interval: 5s
      unhealthyThreshold: 3
      healthyThreshold: 1
