---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname adguard-home
spec:
  targetNamespace: dns-private
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/dns-private/adguard-home"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
  - name: secret
    namespace: dns-private
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: global-config
    namespace: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: cluster-secrets
    - kind: Secret
      name: dns-private-secret
