---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: opencloud-secret
    creationPolicy: Owner
  data:
  - secretKey: IDM_ADMIN_PASSWORD
    remoteRef:
      key: /default/opencloud/idm-admin-password
  - secretKey: IDM_IDPSVC_PASSWORD
    remoteRef:
      key: /default/opencloud/idm-admin-password
  - secretKey: IDP_LDAP_BIND_PASSWORD
    remoteRef:
      key: /default/opencloud/idm-admin-password
