# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: searxng-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Injected into settings.yml by init container
        GITHUB_TOKEN: "{{ .github_pat }}"
        SECRET_KEY: "{{ .secret_key }}"
  data:
  - secretKey: github_pat
    remoteRef:
      key: /default/searxng/github-pat
  - secretKey: secret_key
    remoteRef:
      key: /default/searxng/secret-key
