---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
- ../../components/common
- ../../components/drift-detection
resources:
# TEMPORARY: Testing if Victoria Metrics/Logs writing to Ceph causes write amplification that
# contributes to stuck terminating pods. Disabled to establish baseline cluster behavior.
#
# Recommended action when this is reenabled: Put metrics and logs storage on hostpath with node
# selector for worker nodes.
#
# - ./victoria-metrics-k8s-stack/ks.yaml
# - ./victoria-logs-single/ks.yaml
- ./grafana/ks.yaml
- ./gatus/ks.yaml
- ./vmrules
