# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-s3-operator
  namespace: flux-system
spec:
  interval: 5m
  ref:
    tag: latest
  url: oci://ghcr.io/rcdailey/garage-s3-operator-manifests
