---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../../components/volsync
resources:
- ./externalsecret.yaml
- ./helmrelease.yaml
# - ./oauth-scope-injection.yaml  # Disabled for testing fixed Android app
- ./pvc.yaml
- ./referencegrant.yaml
configMapGenerator:
- name: authelia-config
  files:
  - ./config/configuration.yaml
  - ./config/users.yaml
  - ./config/oidc-base.yaml.tmpl
  - ./config/oidc-clients.yaml.tmpl
  options:
    disableNameSuffixHash: true
