---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./externalsecret.yaml
- ./httproute.yaml
- ./grafana.yaml
- ./grafanadatasource.yaml
- ./dashboards/grafanadashboard.yaml
configMapGenerator:
- name: container-memory-usage-dashboard
  files:
  - container-memory-usage.json=dashboards/container-memory-usage.json
  options:
    disableNameSuffixHash: true
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
