# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:hh4h1lyUYPMNzQ==,iv:pI3dHPEN9YGGRTq25C7PA2C8Fo9Br6Is+A3/uQGbUnw=,tag:1OATeRMHyzHFwyEXNE5cYw==,type:str]
sops:
  age:
    - recipient: age1mxtch0ys4up27h99gjd69w42wuulgavhqyq79q3r4c7yxyj24yuqnjfl0j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NjdwZ3lLUUU3TS9sVGZX
        VVFuRG9sOHNqZm8vZGxGWGZrazZVY29VRGtBCk5kWmxkNlNXYW5TbTFDTTB6eVkw
        RG1SL2ZickN1ZXlsOEFZbEdnOFhwbEkKLS0tIHpNeXJuV0t3Z2hFKzg1YnJ4YlJt
        UU11M3lHVnk3ekZ5N0VPYkFmNjN0Z28K7UhNeERrrMsx+aXM0PyumMhAfuI90iC4
        EWkdQR1IuTwE7DvtYXUPOS1YpkXOi+YxUsVcd0fomCcgLliyTZ0m6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T22:31:07Z"
  mac: ENC[AES256_GCM,data:fI8czsfMN1NhjvRDEOZyP7hTDf2lZb2lyaZpCuYYNDR7EBgsGjVIAif2JsLULLCvJL2SQVU1jxbxazzChjIZnPcFbFNrqM2XYhNQ2WG86CZzYFKmA8rD1kwwsJcinQCmzPnTUIaevMmGVdhCY/Vu5Smj9RkVsJCV1YfO1siIs6U=,iv:vIwBswq3j7B2+VQ/cEF3biFcfOhUJZGEA/agvBxcZMA=,tag:ix1gLCb1cFtIKXuEOvQIXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
