---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./backend-traffic-policy.yaml
- ./certificate.yaml
- ./client-traffic-policy.yaml
- ./gatewayclass.yaml
- ./helmrelease.yaml
- ./envoyproxy-config.yaml
- ./internal.yaml
- ./external.yaml
- ./external-gateway-service.yaml
- ./grafanadashboard.yaml
