---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service.json
apiVersion: v1
kind: Service
metadata:
  name: opensprinkler
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/endpoints.json
apiVersion: v1
kind: Endpoints
metadata:
  name: opensprinkler
subsets:
- addresses:
  - ip: 192.168.2.108
  ports:
  - name: http
    port: 80
    protocol: TCP
