---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./backendtrafficpolicy.yaml
- ./helmrelease.yaml
- ./ks.yaml
- ./pvc.yaml
- ./resourceclaimtemplate.yaml
- ./loadbalancer-service.yaml
configMapGenerator:
- name: plex-victorialogs-rules
  files:
  - plex.yaml=./logrule.yaml
  options:
    labels:
      victorialogs_rule: "true"
- name: plex-vector-config
  files:
  - vector.yaml=./config/vector.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
